In [6]:
import pandas as pd
import ast

In [2]:
allData = pd.read_csv('data/CombinedData.csv')
allData

,QuestionText,QType,Answer,AnswerChoices,Year,Tags,Description
0,Will advanced LIGO announce discovery of gravi...,binary,no,NaN,2016,"['research impact', 'scientific discoveries', ...",NaN
1,Will SpaceX successfully land a Falcon 9 rocke...,binary,no,NaN,2016,"['app success', 'technological advances', 'phy...",NaN
2,Will we confirm evidence for megastructures or...,binary,no,NaN,2016,"['scientific discoveries', 'phys sci astro an...",NaN
3,Will Lockheed Martin and Skunkworks announce a...,binary,no,NaN,2019,"['research impact', 'technological advances', ...",NaN
4,The FAA to soon open the door to commercial us...,binary,no,NaN,2016,"['research impact', 'technological advances', ...",NaN
...,...,...,...,...,...,...,...
7921,"Between 3 October 2019 and 29 November 2019, w...",binary,no,NaN,2019,"['Idiosyncratic', 'Politics', 'International R...",The United Nations (UN) originally scheduled a...
7922,Will the PITF Worldwide Atrocities Dataset rec...,binary,yes,NaN,2019,"['PITF atrocities with non-state perpetrator',...","This question will resolve as ""yes"" if the Pol..."
7923,Will ACLED record any civilian fatalities in R...,binary,yes,NaN,2019,"['ACLED civilian fatalities', 'Politics', 'Int...",The Armed Conflict Location and Event Dataset ...
7924,Will ACLED record any civilian fatalities in S...,binary,yes,NaN,2019,"['ACLED civilian fatalities', 'Politics', 'Int...",The Armed Conflict Location and Event Dataset ...
7925,Will there be a significant day-over-day incre...,binary,yes,NaN,2019,"['Google Trends', 'Politics', 'International R...",Google Trends tracks how often a particular se...

In [5]:
data = allData[allData['QType']=='continuous']
data

,QuestionText,QType,Answer,AnswerChoices,Year,Tags,Description
218,How many Federally Insured Commercial Banks in...,continuous,0.42049,"{'type': 'continuous', 'scale': {'max': 5500, ...",2018,['business'],NaN
219,When will an AI system score an impressive def...,continuous,0.376394712945308,"{'type': 'continuous', 'scale': {'max': '2030-...",2019,"['comp sci ai and machinelearning', 'computin...",[Starcraft 2](http://us.battle.net/sc2/en/) (S...
220,When will programs write programs for us?,continuous,0.408719469965848,"{'type': 'continuous', 'scale': {'max': '2050-...",2021,"['technological advances', 'comp sci ai and m...","Since the early days of ""machine code"" program..."
227,When will the first exaflop performer appear?,continuous,0.8494524711676366,"{'type': 'continuous', 'scale': {'max': '2025-...",2022,['computing computers'],NaN
229,When will the first law concerning artificial ...,continuous,0.2603349902641257,"{'type': 'continuous', 'scale': {'max': '2060-...",2021,"['computing ai', 'law legislation', 'series ...","As of now, there are to the author's knowledge..."
...,...,...,...,...,...,...,...
7830,What will be the 7-day moving average of daily...,continuous,0.16866666666666666,"{'max': 15000, 'min': 0, 'deriv_ratio': 1}",2022,"['Novel Coronavirus (Covid-19)', 'Tournament -...",Following the decline of Omicron wave in Virgi...
7831,What will be the 7-day moving average of daily...,continuous,0.21453333333333333,"{'max': 15000, 'min': 0, 'deriv_ratio': 1}",2022,"['Novel Coronavirus (Covid-19)', 'Tournament -...",Following the decline of Omicron wave in Virgi...
7832,What will be the 7-day moving average of curre...,continuous,0.069975,"{'max': 4000, 'min': 0, 'deriv_ratio': 1}",2022,"['Novel Coronavirus (Covid-19)', 'Tournament -...","Nationwide, new COVID-19 hospitalizations have..."
7833,What will be the 7-day moving average of curre...,continuous,0.1211,"{'max': 4000, 'min': 0, 'deriv_ratio': 1}",2022,"['Novel Coronavirus (Covid-19)', 'Tournament -...","Nationwide, new COVID-19 hospitalizations have..."
7838,[Short Fuse] How much money will be awarded to...,continuous,0.54175,"{'max': 100000000, 'min': -100000000, 'deriv_r...",2022,"['Short-fuse', 'Social issues â€“ Crime and Viol...","From the wikipedia entry John C. Depp, II v. A..."

In [9]:
maxes = []
mins = []
for choice in list(data['AnswerChoices']):
    choice = ast.literal_eval(choice)
    if 'scale' in choice:
        maxes.append(choice['scale']['max'])
        mins.append(choice['scale']['min'])
    else:
        maxes.append(choice['max'])
        mins.append(choice['min'])

In [11]:
maxes[0]

5500

In [12]:
mins[0]

4500